#!/usr/bin/bash

ROOT=$(cd $(dirname $0) ; pwd)
RELEASE_NAME=$(${ROOT}/json release-name < ${ROOT}/build.spec)
if [[ -z ${RELEASE_NAME} ]]; then
    # Use git branch name of repo
    RELEASE_NAME=$(cd ${ROOT} && git branch | grep "^* " | cut -d' ' -f2)
fi
if [[ -z ${RELEASE_NAME} ]]; then
    RELEASE_NAME="unknown"
fi
BUILDSTAMP=`TZ=UTC date "+%Y%m%dT%H%M%SZ"`; export BUILDSTAMP 
FILENAME=agents-${RELEASE_NAME}-${BUILDSTAMP}.sh
MD5_FILE=agents-${RELEASE_NAME}-${BUILDSTAMP}.md5sum
TMP=/var/tmp

set -e

./build_agents

(cat <<__EOF__
#!/bin/sh
if [ \`pwd\` != '$TMP' ]; then
  cd $TMP
fi
__EOF__
)> $FILENAME

(./shar -D -n "Joyent" agents | grep -v '^exit 0'; cat <<EOF

if [[ -f agents/install.sh ]]; then
    (cd agents && /usr/bin/bash ./install.sh)
fi

# Delete agents directory.
rm -fr agents

exit 0
EOF
)>> $FILENAME

md5sum $FILENAME | cut -d' ' -f 1 > $MD5_FILE

if [ ! -z "$COAL_PUBLISH" ]; then
    scp $MD5_FILE $FILENAME jill@coal.joyent.us:/data/coal/live_147/ur-scripts/
fi
