#!/bin/bash

# Git clone and build each of the agents. Depends on passwordless access to the
# Joyent repos.

set -e
set -x

export CC=gcc

DIRNAME=`dirname $0`
ROOT=`cd $DIRNAME && pwd`
DEFAULT_CHECKOUT="origin/release-20110623"
GMAKE=gmake

if [[ $(uname -s) == 'Linux' ]]; then
    BUILD_SPEC="hvm.build.spec"
    GMAKE=make
else
    BUILD_SPEC="build.spec"
fi

build() {
    REPO=$1
    NAME=$2
    CHECKOUT=$3
    TARGET=$4
    TARBALL=$5
    OUTPUT=$6

    if [ -z "$NAME" ]; then
        NAME=$1
    fi

    if [ -z "$CHECKOUT" ]; then
        CHECKOUT=$DEFAULT_CHECKOUT
    fi

    if [ -z "$TARGET" ]; then
        TARGET=npm
    fi

    if [ -z "$TARBALL" ]; then
        TARBALL=$NAME.tgz
    fi

    if [ ! -d "$REPO" ]; then
    	git clone git@git.joyent.com:$REPO.git
    fi

    (cd $REPO && git fetch && git checkout $CHECKOUT)
    (cd $REPO && git submodule update --init)

    (cd $REPO && ${GMAKE} $TARGET)
    cp $REPO/$TARBALL agents/$OUTPUT
}

fetch() {
    name=$1
    branch=$2
    pattern=$3

    pkg_url=$packages_url/$name/$branch

    if [[ -z "$pattern" ]]; then
        filter="$name"
    else
        filter="$pattern"
    fi

    # Determine latest package
    latest_pkg=$(curl -k -sS ${pkg_url}/ \
        | grep "href=\"" \
        | cut -d'"' -f2 \
        | grep "$filter" \
        | sort | tail -1
        )

    # Download it to the agents/ directory
    (cd agents && curl ${SPEED_LIMIT} --progress-bar -k -O $pkg_url/${latest_pkg})
}

num_pkgs=$(${ROOT}/json packages.length < ${ROOT}/${BUILD_SPEC})
if [[ -n ${num_pkgs} ]] && [[ ${num_pkgs} -lt 1 ]]; then
    echo "FATAL: no agents listed in ${ROOT}/${BUILD_SPEC}"
    exit 1
fi

packages_url=$(${ROOT}/json "packages-url" < ${ROOT}/${BUILD_SPEC})
idx=0
while [[ ${idx} -lt ${num_pkgs} ]]; do
    name=$(${ROOT}/json packages[${idx}].name < ${ROOT}/${BUILD_SPEC})
    branch=$(${ROOT}/json packages[${idx}].branch < ${ROOT}/${BUILD_SPEC})
    pattern=$(${ROOT}/json packages[${idx}].pattern < ${ROOT}/${BUILD_SPEC})

    fetch "${name}" "${branch}" "${pattern}"

    idx=$((${idx} + 1))
done

exit 0
