#!/bin/bash
#
# Make an agents shar (agents-$BUILDSTAMP.sh) package.
#
# Examples:
#
#    # Build name "release-20110714", includes all agents by default.
#    # Source dir (-d) is a local path or a URL.
#    bin/mk-agents-shar -b release-20110714 \
#        -d https://guest:pass@bits.joyent.us/builds
#
#    # Default build name is "master", default source dir is as above.
#    bin/mk-agents-shar
#
#    # Using built agent packages from a local "bits" dir.
#    bin/mk-agents-shar -b release-20110714 -d ../../bits
#

if [ "$TRACE" != "" ]; then
    export PS4='${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
    set -o xtrace
fi
set -o errexit
set -o pipefail



#---- config/globals

TOP=$(cd $(dirname $0)/; pwd)

# Put the Manta tools that 'make deps' installed for us first.
export PATH="${TOP}/node_modules/manta/bin:${PATH}"

# --- Manta config
if [[ -z "$MANTA_KEY_ID" ]]; then
    export MANTA_KEY_ID=`ssh-keygen -l -f ~/.ssh/id_rsa.pub | awk '{print $2}' | tr -d '\n'`
fi
if [[ -z "$MANTA_USER" ]]; then
    export MANTA_USER="Joyent_Dev";
fi
export MANTA_URL=https://us-east.manta.joyent.com
export MANTA_BASE="/Joyent_Dev/stor/builds"

[[ -n ${MANTA_KEY_ID} ]] || fatal "missing MANTA_KEY_ID"
[[ -n ${MANTA_USER} ]] || fatal "missing MANTA_USER"
[[ -n ${MANTA_URL} ]] || fatal "missing MANTA_URL"
[[ -n ${MANTA_BASE} ]] || fatal "missing MANTA_BASE"

DEFAULT_SOURCE_DIR=${MANTA_BASE}
DEFAULT_BUILD_NAMES=master
ALL_AGENTS=$(cat agents.json | json -a | xargs)

BUILD_DIR=build

if [[ -z "$TIMESTAMP" ]]; then
    TIMESTAMP=$(date -u "+%Y%m%dT%H%M%SZ")
fi
# Need GNU awk for multi-char arg to "-F".
AWK=$((which gawk 2>/dev/null | grep -v "^no ") || which awk)
GITDESCRIBE=g$(git describe --all --long --dirty | ${AWK} -F'-g' '{print $NF}')

SHAR=${TOP}/shar
if [[ $(uname -s) == 'Linux' ]]; then
    SHAR=/usr/bin/shar
fi



#---- functions

function fatal {
    echo "$(basename $0): error: $1"
    exit 1
}

function usage() {
    if [[ -n "$1" ]]; then
        echo "error: $1"
        echo ""
    fi
    echo "Usage:"
    echo "  mk-agents-shar [OPTIONS] [AGENTS...]"
    echo ""
    echo "Options:"
    echo "  -h      print this help and exit"
    echo "  -b      build name(s), e.g. 'master' (the default), 'release-20110714'"
    echo "          Typically the name of the repo branch. Note this can"
    echo "          be multiple space-separated build names (e.g. "
    echo "          'feature1 master'). Each name is attempted to find an "
    echo "          agent package for each agent."
    echo "  -d      source dir, a local path or URL"
    echo "          (default is <$DEFAULT_SOURCE_DIR>)"
    echo "  -o      output directory to which to write results, default is 'build'"
    echo ""
    echo "Build an agents shar. Without any given 'AGENTS' strings all agents"
    echo "are included."
}


# Fetch the latest agent package matching the given name and buildname.
#
# Here "latest" is just a lexographical sort, so we are relying on agent
# package names to be sortable (currently that is acheived by using a
# ISO timestamp in the package names).
function fetch_agent_package() {
    local name=$1         # e.g. "ca/cabase" or "agents/provisioner-v2/provisioner-v2"
    local build_names=$2  # e.g. "release-20110901" or "master"
                          #     or "feature1 master" to try a feature1 branch
                          #     with master fallback if not available
    local from_dir=$3     # See example below.
    local to_dir=$4
    local success=
    local dir=$(dirname $name)

    for one_build_name in $build_names; do
        local base_pattern="^$(basename $name)-$one_build_name-.*"

        if [[ ! -d ${from_dir} ]]; then      # Not manta
            # E.g. "ca/cabase-master-20110728T214412Z-4d6102d.tar.gz"
            local scope=${name%%/*}    # "a/b/c" -> "a"
            local latest_dir=$(mget -q ${from_dir}/${scope}/${one_build_name}-latest)

            [[ -n ${latest_dir} ]] || fatal "Unable to determine latest build of ${name}"

            local latest_name=$(mls ${latest_dir}/${dir} \
                | grep "${base_pattern}" \
                | sort | tail -1
            )
            if [[ -z "${latest_name}" ]]; then
                echo "WARN: could not find '${base_pattern}' in '${url_dir}'"
            else
                echo "Downloading '${latest_dir}/${dir}/${latest_name}' to '${to_dir}'."
                mget -q -o ${to_dir}/${latest_name} ${latest_dir}/${dir}/${latest_name}
                if [[ $? == 0 ]]; then
                    success=1
                    break
                fi
            fi
        else
            # Local bits dir 'from_dir' example:
            #   /home/jill/joy/mountain-gorilla/bits
            # where name='ca/cabase' is at:
            #   /home/jill/joy/mountain-gorilla/bits/ca/cabase-$branch-*
            # where name='agents/metadata/metadata' is at:
            #   /home/jill/joy/mountain-gorilla/bits/agents/metadata/metadata-$branch-*
            local latest_name=$(ls -1 ${from_dir}/${dir}/ | grep "${base_pattern}" | sort | tail -1)
            if [[ -z "${latest_name}" ]]; then
                echo "WARN: could not find '${base_pattern}' in '${from_dir}/${dir}'"
            else
                local latest_path="${from_dir}/${dir}/${latest_name}"
                echo "Copying '${latest_path}' to '${to_dir}'."
                cp ${latest_path} ${to_dir}
                success=1
                break
            fi
        fi
    done

    if [[ -z "$success" ]]; then
        fatal "could not find '$name' agent package with build name '$build_names' in '$from_dir'"
    fi
}

function mk_shar_imgmanifest() {
    NAME=agentsshar
    TMPDIR=/tmp
    GITDESCRIBE=g$(git describe --all --long --dirty | ${AWK} -F'-g' '{print $$NF}')
    STAMP=${BRANCH}-${TIMESTAMP}-${GITDESCRIBE}
    RELEASE_FILE=$(basename `ls ${TOP}/build/agents-*.sh | head -n 1`)

    RELEASE_MANIFEST=${NAME}.imgmanifest;
    mkdir -p ${TMPDIR}/${NAME}
    uuid -v4 > ${TMPDIR}/${NAME}/image_uuid
    cat $(TOP)/manifest.tmpl | sed \
            -e "s/UUID/\$$(cat ${TMPDIR}/${NAME}/image_uuid)/" \
            -e "s/NAME/\$$(json name < ${TOP}/package.json)/" \
            -e "s/VERSION/1/" \
            -e "s/BUILDSTAMP/$(STAMP)/" \
            -e "s/SIZE/\$$(stat --printf="%s" ${TOP}/build/${RELEASE_FILE})/" \
            -e "s/SHA/\$$(openssl sha1 ${TOP}/build/${RELEASE_FILE} \
                | cut -d ' ' -f2)/" \
            > ${BUILD_DIR}/${RELEASE_MANIFEST}
}


function mk_agents_shar() {
    local agents="$1"
    local build_names="$2"
    local source_dir="$3"
    local output_dir="$4"
    echo "Make '$build_names' agents shar (timestamp $TIMESTAMP) from '${source_dir}'."

    # Get all the agents files and boilerplate into the build dir.
    local build_dir=$BUILD_DIR/agents
    rm -rf $build_dir
    mkdir -p $build_dir
    cp install.sh $build_dir
    for agent in $agents; do
        fetch_agent_package "$agent" "$build_names" "$source_dir" "$build_dir"
    done

    # Create the shar.
    local first_build_name=$(echo $build_names | xargs -n1 2>/dev/null | head -1)
    local tmp=/var/tmp
    local sh_filename=agents-$first_build_name-$TIMESTAMP-$GITDESCRIBE.sh
    cd $BUILD_DIR

    (cat <<__EOF__
#!/bin/sh
if [ \`pwd\` != '$tmp' ]; then
  cd $tmp
fi
__EOF__
)> $sh_filename

    (${SHAR} -D -n "Joyent" agents | grep -v '^exit 0'; cat <<EOF

set -o errexit
set -o pipefail

if [[ -f agents/install.sh ]]; then
    (cd agents && /bin/bash ./install.sh)
fi

# Delete agents directory.
rm -fr agents

exit 0
EOF
)>> $sh_filename

    # Create the md5sums file.
    local md5sum_filename=agents-$first_build_name-$TIMESTAMP-$GITDESCRIBE.md5sum
    openssl dgst -md5 $sh_filename | cut -d' ' -f 2 > $md5sum_filename

    mk_shar_imgmanifest
    local imgmanifest_filename=$(ls $BUILD_DIR/*.imgmanifest | head -n 1)

    # Copy bits to output dir, if necessary.
    cd $TOP
    if [[ "$output_dir" != "$BUILD_DIR" ]]; then
        cp $BUILD_DIR/$sh_filename $output_dir/
        cp $BUILD_DIR/$md5sum_filename $output_dir/
        cp $BUILD_DIR/$imgmanifest_filename $output_dir/
    fi
    echo "Created '$output_dir/$sh_filename'."
    echo "Created '$output_dir/$md5sum_filename'."
    echo "Created '$output_dir/$imgmanifest_filename'."
}



#---- mainline

# Process arguments.
build_names=$DEFAULT_BUILD_NAMES
source_dir=$DEFAULT_SOURCE_DIR
output_dir=$BUILD_DIR
while getopts "hb:d:o:" c; do
    case "$c" in
    h)
        usage
        exit 0
        ;;
    b)
        build_names=$OPTARG
        ;;
    d)
        source_dir=$OPTARG
        ;;
    o)
        output_dir=$OPTARG
        ;;
    *)
        usage "illegal option -- $OPTARG"
        exit 1
        ;;
    esac
done
shift $((OPTIND - 1))

agents="$*"
if [[ -z "$agents" ]]; then
    agents="$ALL_AGENTS"
fi

mk_agents_shar "$agents" "$build_names" "$source_dir" "$output_dir"
exit $?
